[package]
# Keep in sync with `AXIS_PACKAGE` in the Makefile.
name = "tailnet"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "An ACAP that puts an Axis device on a Tailscale network"
publish = false

[lints]
workspace = true

[dependencies]
acap-logging = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
easy-acap-dirs = { workspace = true }
log = { workspace = true }
nix = { workspace = true, features = ["fs", "hostname"] }
rustls = { workspace = true }
rustls-openssl = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tailscale = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "io-util", "signal", "time"] }
tokio-util = { workspace = true }
tower-http = { workspace = true, features = ["fs"] }
tracing = { workspace = true, features = ["log"] }
url = { workspace = true }



[build-dependencies]
serde_json = { workspace = true }
